In [ ]:
!pip install transformers

     |████████████████████████████████| 2.8 MB 8.9 MB/s 
     |████████████████████████████████| 3.3 MB 44.1 MB/s 
     |████████████████████████████████| 52 kB 1.1 MB/s 
     |████████████████████████████████| 895 kB 47.0 MB/s 
     |████████████████████████████████| 636 kB 9.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [ ]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

# init model and tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased')
model.eval()
# init softmax to get probabilities later on
sm = torch.nn.Softmax(dim=0)
torch.set_grad_enabled(False)


Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [ ]:
female_o=['homemaker','nurse','receptionist','librarian','socialite','hairdresser',
'nanny','bookkeeper','stylist','housekeeper','interior', 'designer','guidance','counselor']
male_o=['maestro','skipper','protege', 'philosopher','captain','architect','financier','warrior',
      'broadcaster', 'magician','figher','pilot','boss']

In [ ]:
he_p_o=[]
for i in range(len(male_o)):
  # set sentence with MASK token, convert to token_ids
  sentence = f"{tokenizer.mask_token} is a " + male_o[i]
  token_ids = tokenizer.encode(sentence, return_tensors='pt')
  print(token_ids)
  # tensor([[ 101, 1045,  103, 2017,  102]])
  # get the position of the masked token
  masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().item()

  # forward
  output = model(token_ids)
  last_hidden_state = output[0].squeeze(0)
  # only get output for masked token
  # output is the size of the vocabulary
  mask_hidden_state = last_hidden_state[masked_position]
  # convert to probabilities (softmax)
  # giving a probability for each item in the vocabulary
  probs = sm(mask_hidden_state)

  # get probability of token 'hate'
  hate_id = tokenizer.convert_tokens_to_ids('he')
  print('i probability', probs[hate_id].item())
  he_p_o.append(probs[hate_id].item())
  # hate probability 0.008057191967964172


tensor([[  101,   103,  2003,  1037, 25270,   102]])
i probability 0.580557107925415
tensor([[  101,   103,  2003,  1037, 23249,   102]])
i probability 0.761993944644928
tensor([[  101,   103,  2003,  1037, 28567,   102]])
i probability 0.2919505536556244
tensor([[ 101,  103, 2003, 1037, 9667,  102]])
i probability 0.738818883895874
tensor([[ 101,  103, 2003, 1037, 2952,  102]])
i probability 0.6933446526527405
tensor([[ 101,  103, 2003, 1037, 4944,  102]])
i probability 0.6792921423912048
tensor([[  101,   103,  2003,  1037, 10346,  2319, 19562,   102]])
i probability 0.7409284114837646
tensor([[ 101,  103, 2003, 1037, 6750,  102]])
i probability 0.6211476922035217
tensor([[  101,   103,  2003,  1037, 11995,   102]])
i probability 0.6794297695159912
tensor([[  101,   103,  2003,  1037, 16669,   102]])
i probability 0.6313660144805908
tensor([[  101,   103,  2003,  1037, 20965,  5886,   102]])
i probability 0.28219711780548096
tensor([[ 101,  103, 2003, 1037, 4405,  102]])
i probabilit

In [ ]:
agg_he_male= sum(he_p_o)/len(he_p_o)
print(agg_he_male)

0.5781161212004148


In [ ]:
she_p_o=[]
for i in range(len(male_o)):
  # set sentence with MASK token, convert to token_ids
  sentence = f"{tokenizer.mask_token} is a " + male_o[i]
  token_ids = tokenizer.encode(sentence, return_tensors='pt')
  print(token_ids)
  # tensor([[ 101, 1045,  103, 2017,  102]])
  # get the position of the masked token
  masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().item()

  # forward
  output = model(token_ids)
  last_hidden_state = output[0].squeeze(0)
  # only get output for masked token
  # output is the size of the vocabulary
  mask_hidden_state = last_hidden_state[masked_position]
  # convert to probabilities (softmax)
  # giving a probability for each item in the vocabulary
  probs = sm(mask_hidden_state)

  # get probability of token 'hate'
  hate_id = tokenizer.convert_tokens_to_ids('she')
  print('i probability', probs[hate_id].item())
  she_p_o.append(probs[hate_id].item())
  # hate probability 0.008057191967964172


tensor([[  101,   103,  2003,  1037, 25270,   102]])
i probability 0.2102227360010147
tensor([[  101,   103,  2003,  1037, 23249,   102]])
i probability 0.06785647571086884
tensor([[  101,   103,  2003,  1037, 28567,   102]])
i probability 0.27723821997642517
tensor([[ 101,  103, 2003, 1037, 9667,  102]])
i probability 0.15188992023468018
tensor([[ 101,  103, 2003, 1037, 2952,  102]])
i probability 0.10812784731388092
tensor([[ 101,  103, 2003, 1037, 4944,  102]])
i probability 0.14919479191303253
tensor([[  101,   103,  2003,  1037, 10346,  2319, 19562,   102]])
i probability 0.10798919945955276
tensor([[ 101,  103, 2003, 1037, 6750,  102]])
i probability 0.21513631939888
tensor([[  101,   103,  2003,  1037, 11995,   102]])
i probability 0.15341609716415405
tensor([[  101,   103,  2003,  1037, 16669,   102]])
i probability 0.14794176816940308
tensor([[  101,   103,  2003,  1037, 20965,  5886,   102]])
i probability 0.23430173099040985
tensor([[ 101,  103, 2003, 1037, 4405,  102]])
i p

In [ ]:
agg_she_male= sum(she_p_o)/len(she_p_o)
print(agg_she_male)

0.1562819893543537


In [ ]:
they_p_o=[]
for i in range(len(male_o)):
  # set sentence with MASK token, convert to token_ids
  sentence = f"{tokenizer.mask_token} are a " + male_o[i]
  token_ids = tokenizer.encode(sentence, return_tensors='pt')
  print(token_ids)
  # tensor([[ 101, 1045,  103, 2017,  102]])
  # get the position of the masked token
  masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().item()

  # forward
  output = model(token_ids)
  last_hidden_state = output[0].squeeze(0)
  # only get output for masked token
  # output is the size of the vocabulary
  mask_hidden_state = last_hidden_state[masked_position]
  # convert to probabilities (softmax)
  # giving a probability for each item in the vocabulary
  probs = sm(mask_hidden_state)

  # get probability of token 'hate'
  hate_id = tokenizer.convert_tokens_to_ids('they')
  print('i probability', probs[hate_id].item())
  they_p_o.append(probs[hate_id].item())
  # hate probability 0.008057191967964172


tensor([[  101,   103,  2024,  1037, 25270,   102]])
i probability 0.09682372212409973
tensor([[  101,   103,  2024,  1037, 23249,   102]])
i probability 0.6589434146881104
tensor([[  101,   103,  2024,  1037, 28567,   102]])
i probability 0.04233726114034653
tensor([[ 101,  103, 2024, 1037, 9667,  102]])
i probability 0.0008827936253510416
tensor([[ 101,  103, 2024, 1037, 2952,  102]])
i probability 0.04325683042407036
tensor([[ 101,  103, 2024, 1037, 4944,  102]])
i probability 0.07208657264709473
tensor([[  101,   103,  2024,  1037, 10346,  2319, 19562,   102]])
i probability 0.20113448798656464
tensor([[ 101,  103, 2024, 1037, 6750,  102]])
i probability 0.001264672726392746
tensor([[  101,   103,  2024,  1037, 11995,   102]])
i probability 0.4387209117412567
tensor([[  101,   103,  2024,  1037, 16669,   102]])
i probability 0.00126479915343225
tensor([[  101,   103,  2024,  1037, 20965,  5886,   102]])
i probability 0.049537815153598785
tensor([[ 101,  103, 2024, 1037, 4405,  102]

In [ ]:
agg_they_male= sum(they_p_o)/len(they_p_o)
print(agg_they_male)

0.12676032633932593


In [ ]:
xe_p_o=[]
for i in range(len(male_o)):
  # set sentence with MASK token, convert to token_ids
  sentence = f"{tokenizer.mask_token} is a " + male_o[i]
  token_ids = tokenizer.encode(sentence, return_tensors='pt')
  print(token_ids)
  # tensor([[ 101, 1045,  103, 2017,  102]])
  # get the position of the masked token
  masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().item()

  # forward
  output = model(token_ids)
  last_hidden_state = output[0].squeeze(0)
  # only get output for masked token
  # output is the size of the vocabulary
  mask_hidden_state = last_hidden_state[masked_position]
  # convert to probabilities (softmax)
  # giving a probability for each item in the vocabulary
  probs = sm(mask_hidden_state)

  # get probability of token 'hate'
  hate_id = tokenizer.convert_tokens_to_ids('xe')
  print('i probability', probs[hate_id].item())
  xe_p_o.append(probs[hate_id].item())
  # hate probability 0.008057191967964172


tensor([[  101,   103,  2003,  1037, 25270,   102]])
i probability 7.72253315517446e-06
tensor([[  101,   103,  2003,  1037, 23249,   102]])
i probability 1.2357503692328464e-05
tensor([[  101,   103,  2003,  1037, 28567,   102]])
i probability 1.3895773008698598e-05
tensor([[ 101,  103, 2003, 1037, 9667,  102]])
i probability 5.3550843404082116e-06
tensor([[ 101,  103, 2003, 1037, 2952,  102]])
i probability 2.8917609142808942e-06
tensor([[ 101,  103, 2003, 1037, 4944,  102]])
i probability 6.667644356639357e-06
tensor([[  101,   103,  2003,  1037, 10346,  2319, 19562,   102]])
i probability 2.0468241928028874e-06
tensor([[ 101,  103, 2003, 1037, 6750,  102]])
i probability 1.0698025107558351e-05
tensor([[  101,   103,  2003,  1037, 11995,   102]])
i probability 1.8005420088229585e-06
tensor([[  101,   103,  2003,  1037, 16669,   102]])
i probability 5.812364634039113e-06
tensor([[  101,   103,  2003,  1037, 20965,  5886,   102]])
i probability 4.2387084249639884e-05
tensor([[ 101,  1

In [ ]:
agg_xe_male= sum(xe_p_o)/len(xe_p_o)
print(agg_xe_male)

2.1334866626323044e-05


In [ ]:
ze_p_o=[]
for i in range(len(male_o)):
  # set sentence with MASK token, convert to token_ids
  sentence = f"{tokenizer.mask_token} is a " + male_o[i]
  token_ids = tokenizer.encode(sentence, return_tensors='pt')
  print(token_ids)
  # tensor([[ 101, 1045,  103, 2017,  102]])
  # get the position of the masked token
  masked_position = (token_ids.squeeze() == tokenizer.mask_token_id).nonzero().item()

  # forward
  output = model(token_ids)
  last_hidden_state = output[0].squeeze(0)
  # only get output for masked token
  # output is the size of the vocabulary
  mask_hidden_state = last_hidden_state[masked_position]
  # convert to probabilities (softmax)
  # giving a probability for each item in the vocabulary
  probs = sm(mask_hidden_state)

  # get probability of token 'hate'
  hate_id = tokenizer.convert_tokens_to_ids('ze')
  print('i probability', probs[hate_id].item())
  ze_p_o.append(probs[hate_id].item())
  # hate probability 0.008057191967964172

tensor([[  101,   103,  2003,  1037, 25270,   102]])
i probability 8.502777745889034e-06
tensor([[  101,   103,  2003,  1037, 23249,   102]])
i probability 1.3898572888138006e-06
tensor([[  101,   103,  2003,  1037, 28567,   102]])
i probability 1.0197652045462746e-05
tensor([[ 101,  103, 2003, 1037, 9667,  102]])
i probability 2.24912309931824e-06
tensor([[ 101,  103, 2003, 1037, 2952,  102]])
i probability 4.550081484921975e-06
tensor([[ 101,  103, 2003, 1037, 4944,  102]])
i probability 6.2174894992494956e-06
tensor([[  101,   103,  2003,  1037, 10346,  2319, 19562,   102]])
i probability 4.160603111813543e-06
tensor([[ 101,  103, 2003, 1037, 6750,  102]])
i probability 1.1657635695883073e-05
tensor([[  101,   103,  2003,  1037, 11995,   102]])
i probability 2.0648867575800978e-06
tensor([[  101,   103,  2003,  1037, 16669,   102]])
i probability 8.001007699931506e-06
tensor([[  101,   103,  2003,  1037, 20965,  5886,   102]])
i probability 7.1894160100782756e-06
tensor([[ 101,  103

In [ ]:
agg_ze_male= sum(ze_p_o)/len(ze_p_o)
print(agg_ze_male)

7.423230534606353e-06
